### ISSUE TITLE
Item codes starting with numbers end in compile error in D2RMM

### ISSUE THREAD

**Issue by electroretard** [Caedendi/D2RMM-Loot-Filter-Extended#3]
I'm trying to create an entry for highlighting a phase blade, which has item code 7cr.

Added the following line in the filter:

		this.items.7cr = `${RED}!!!${WHITE}Phase Blade`;

However, this does not work and D2RMM just returns a compile error.

How can I filter item codes starting with numbers?

**Comment by Caedendi** [comment]
The line itself looks good, but I'm not the best with js so you could be right that it won't work for codes starting with a number. First question would be if you added the line in the right spot because I don't know by heart in what file they put phase blades. Something else you can try is this:
```
this.items.["7cr"] = `${RED}!!!${WHITE}Phase Blade`;
```

**Comment by electroretard** [comment]
Thanks for the quick reply, that almost solved it! The correct line to use is:

	this.items["7cr"] = `${RED}!!!${WHITE}Phase Blade`;

Cheers!
